image:
  file: ./devops/.gitpod.Dockerfile
tasks:
  - init: pnpm install
    command: pnpm install
# Ports to expose on workspace startup
ports:
  - port: 3000
    visibility: public
vscode:
  extensions:
    - PKief.material-icon-theme
    - esbenp.prettier-vscode
