image: gitpod/workspace-full
workspaceLocation: "."
tasks:
  # - name: install the remote-signer
  #   before: |
  #     sudo sh -c 'curl https://ipfs.anagolay.network/ipfs/QmVwR17T5oT4SsH1gb8T9L9gHe5CsJz2iwhbhWCwPPHgHR > /usr/local/bin/remote-signer && chmod +x /usr/local/bin/remote-signer' \
  #     && git config --global gpg.program "remote-signer" \
  #     && git config --global commit.gpgsign true
  - init: pnpm install
    command: pnpm install
  - command: bash devops/install-deps.sh
# Ports to expose on workspace startup
ports:
  - port: 3000
    visibility: public
vscode:
  extensions:
    - PKief.material-icon-theme
    - esbenp.prettier-vscode
    - donjayamanne.githistory
    - ms-azuretools.vscode-docker
    - eriklynd.json-tools
    - oliversturm.fix-json
    - GitLab.gitlab-workflow
