version: '3'
services:
  server:
    image: woss/remote-gpg-signing-service
    build: 
      target: main
      context: .
      dockerfile: ./devops/prod.Dockerfile
    volumes:
      - ./keys:/keys
    ports:
      - 31111:3000
