version: '3'
services:
  server:
    image: woss/remote-signer-server:latest
    build:
      target: main
      context: .
      dockerfile: ./devops/prod.Dockerfile
    volumes:
      - ./keys:/keys
    ports:
      - 31111:3000
